name:                padic
version:             0.1.0.0
github:              "githubuser/padic"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/padic#readme>

dependencies:
 - base
 - constraints
 - inflist
 - integer-gmp
 - ghc-prim
 - mod
 - hspec
 - QuickCheck
 - tasty
 - tasty-hunit
 - tasty-quickcheck
 - tasty-expected-failure

library:
  source-dirs: src

tests:
  padic-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - padic
    - hspec
    - QuickCheck
    other-modules:
      - ZSpec
      - QSpec

benchmarks:
  criterion-benchmarks:
    dependencies:
      - criterion
      - padic
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    main: Bench.hs
    source-dirs: bench
